name: Deploy

on:
  push:
    branches:
      - dev
      - testing
      - uat
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DEV_SERVER_KEY: ${{ secrets.DEV_SERVER_KEY }}
      TESTING_SERVER_KEY: ${{ secrets.TESTING_SERVER_KEY }}
      UAT_SERVER_KEY: ${{ secrets.UAT_SERVER_KEY }}
      PROD_SERVER_KEY: ${{ secrets.PROD_SERVER_KEY }}
      DEV_SERVER: ${{ secrets.DEV_SERVER }}
      TESTING_SERVER: ${{ secrets.TESTING_SERVER }}
      UAT_SERVER: ${{ secrets.UAT_SERVER }}
      PROD_SERVER: ${{ secrets.PROD_SERVER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH for dev
        if: github.ref == 'refs/heads/dev'
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEV_SERVER_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to dev
        if: github.ref == 'refs/heads/dev'
        run: bash .dev-gitlab-deploy.sh

      - name: Set up SSH for testing
        if: github.ref == 'refs/heads/testing'
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.TESTING_SERVER_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to testing
        if: github.ref == 'refs/heads/testing'
        run: bash .testing-gitlab-deploy.sh

      - name: Set up SSH for uat
        if: github.ref == 'refs/heads/uat'
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.UAT_SERVER_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to uat
        if: github.ref == 'refs/heads/uat'
        run: bash .uat-gitlab-deploy.sh
    
      - name: Set up SSH for prod
        if: github.ref == 'refs/heads/prod'
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PROD_SERVER_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to prod
        if: github.ref == 'refs/heads/prod'
        run: bash .prod-gitlab-deploy.sh
