image: node:latest

stages:
  - deploy

# Dev deployment job
dev_job:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
  before_script:
    - mkdir -p ~/.ssh
    - echo -e "$DEV_SERVER_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
  script:
    - bash .dev-gitlab-deploy.sh
  environment:
    name: development

# Testing deployment job
testing_job:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "testing"'
  before_script:
    - mkdir -p ~/.ssh
    - echo -e "$TESTING_SERVER_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
  script:
    - bash .testing-gitlab-deploy.sh
  environment:
    name: testing

# UAT deployment job
uat_job:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "uat"'
  before_script:
    - mkdir -p ~/.ssh
    - echo -e "$UAT_SERVER_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
  script:
    - bash .uat-gitlab-deploy.sh
  environment:
    name: uat

# PROD deployment job
uat_job:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "prod"'
  before_script:
    - mkdir -p ~/.ssh
    - echo -e "$PROD_SERVER_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
  script:
    - bash .prod-gitlab-deploy.sh
  environment:
    name: prod
